const wordList = [
    {
        word: "guitar",
        hint: "A musical instrument with strings."
    },
    {
        word: "oxygen",
        hint: "A colorless, odorless gas essential for life."
    },
    {
        word: "mountain",
        hint: "A large natural elevation of the Earth's surface."
    },
    {
        word: "painting",
        hint: "An art form using colors on a surface to create images or expression."
    },
    {
        word: "astronomy",
        hint: "The scientific study of celestial objects and phenomena."
    },
    {
        word: "football",
        hint: "A popular sport played with a spherical ball."
    },
    {
        word: "chocolate",
        hint: "A sweet treat made from cocoa beans."
    },
    {
        word: "butterfly",
        hint: "An insect with colorful wings and a slender body."
    },
    {
        word: "history",
        hint: "The study of past events and human civilization."
    },
    {
        word: "pizza",
        hint: "A savory dish consisting of a round, flattened base with toppings."
    },
    {
        word: "jazz",
        hint: "A genre of music characterized by improvisation and syncopation."
    },
    {
        word: "camera",
        hint: "A device used to capture and record images or videos."
    },
    {
        word: "diamond",
        hint: "A precious gemstone known for its brilliance and hardness."
    },
    {
        word: "adventure",
        hint: "An exciting or daring experience."
    },
    {
        word: "science",
        hint: "The systematic study of the structure and behavior of the physical and natural world."
    },
    {
        word: "bicycle",
        hint: "A human-powered vehicle with two wheels."
    },
    {
        word: "sunset",
        hint: "The daily disappearance of the sun below the horizon."
    },
    {
        word: "coffee",
        hint: "A popular caffeinated beverage made from roasted coffee beans."
    },
    {
        word: "dance",
        hint: "A rhythmic movement of the body often performed to music."
    },
    {
        word: "galaxy",
        hint: "A vast system of stars, gas, and dust held together by gravity."
    },
    {
        word: "orchestra",
        hint: "A large ensemble of musicians playing various instruments."
    },
    {
        word: "volcano",
        hint: "A mountain or hill with a vent through which lava, rock fragments, hot vapor, and gas are ejected."
    },
    {
        word: "novel",
        hint: "A long work of fiction, typically with a complex plot and characters."
    },
    {
        word: "sculpture",
        hint: "A three-dimensional art form created by shaping or combining materials."
    },
    {
        word: "symphony",
        hint: "A long musical composition for a full orchestra, typically in multiple movements."
    },
    {
        word: "architecture",
        hint: "The art and science of designing and constructing buildings."
    },
    {
        word: "ballet",
        hint: "A classical dance form characterized by precise and graceful movements."
    },
    {
        word: "astronaut",
        hint: "A person trained to travel and work in space."
    },
    {
        word: "waterfall",
        hint: "A cascade of water falling from a height."
    },
    {
        word: "technology",
        hint: "The application of scientific knowledge for practical purposes."
    },
    {
        word: "rainbow",
        hint: "A meteorological phenomenon that is caused by reflection, refraction, and dispersion of light."
    },
    {
        word: "universe",
        hint: "All existing matter, space, and time as a whole."
    },
    {
        word: "piano",
        hint: "A musical instrument played by pressing keys that cause hammers to strike strings."
    },
    {
        word: "vacation",
        hint: "A period of time devoted to pleasure, rest, or relaxation."
    },
    {
        word: "rainforest",
        hint: "A dense forest characterized by high rainfall and biodiversity."
    },
    {
        word: "theater",
        hint: "A building or outdoor area in which plays, movies, or other performances are staged."
    },
    {
        word: "telephone",
        hint: "A device used to transmit sound over long distances."
    },
    {
        word: "language",
        hint: "A system of communication consisting of words, gestures, and syntax."
    },
    {
        word: "desert",
        hint: "A barren or arid land with little or no precipitation."
    },
    {
        word: "sunflower",
        hint: "A tall plant with a large yellow flower head."
    },
    {
        word: "fantasy",
        hint: "A genre of imaginative fiction involving magic and supernatural elements."
    },
    {
        word: "telescope",
        hint: "An optical instrument used to view distant objects in space."
    },
    {
        word: "breeze",
        hint: "A gentle wind."
    },
    {
        word: "oasis",
        hint: "A fertile spot in a desert where water is found."
    },
    {
        word: "photography",
        hint: "The art, process, or practice of creating images by recording light or other electromagnetic radiation."
    },
    {
        word: "safari",
        hint: "An expedition or journey, typically to observe wildlife in their natural habitat."
    },
    {
        word: "planet",
        hint: "A celestial body that orbits a star and does not produce light of its own."
    },
    {
        word: "river",
        hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream."
    },
    {
        word: "tropical",
        hint: "Relating to or situated in the region between the Tropic of Cancer and the Tropic of Capricorn."
    },
    {
        word: "mysterious",
        hint: "Difficult or impossible to understand, explain, or identify."
    },
    {
        word: "enigma",
        hint: "Something that is mysterious, puzzling, or difficult to understand."
    },
    {
        word: "paradox",
        hint: "A statement or situation that contradicts itself or defies intuition."
    },
    {
        word: "puzzle",
        hint: "A game, toy, or problem designed to test ingenuity or knowledge."
    },
    {
        word: "whisper",
        hint: "To speak very softly or quietly, often in a secretive manner."
    },
    {
        word: "shadow",
        hint: "A dark area or shape produced by an object blocking the light."
    },
    {
        word: "secret",
        hint: "Something kept hidden or unknown to others."
    },
    {
        word: "curiosity",
        hint: "A strong desire to know or learn something."
    },
    {
        word: "unpredictable",
        hint: "Not able to be foreseen or known beforehand; uncertain."
    },
    {
        word: "obfuscate",
        hint: "To confuse or bewilder someone; to make something unclear or difficult to understand."
    },
    {
        word: "unveil",
        hint: "To make known or reveal something previously secret or unknown."
    },
    {
        word: "illusion",
        hint: "A false perception or belief; a deceptive appearance or impression."
    },
    {
        word: "moonlight",
        hint: "The light from the moon."
    },
    {
        word: "vibrant",
        hint: "Full of energy, brightness, and life."
    },
    {
        word: "nostalgia",
        hint: "A sentimental longing or wistful affection for the past."
    },
    {
        word: "brilliant",
        hint: "Exceptionally clever, talented, or impressive."
    },
    {word:"abruptly", hint:"no hint"},
    {word:"absurd", hint:"no hint"},
    {word:"abyss", hint:"no hint"},
    {word:"affix", hint:"no hint"},
    {word:"askew", hint:"no hint"},
    {word:"avenue", hint:"no hint"},
    {word:"awkward", hint:"no hint"},
    {word:"axiom", hint:"no hint"},
    {word:"azure", hint:"no hint"},
    {word:"bagpipes", hint:"no hint"},
    {word:"bandwagon", hint:"no hint"},
    {word:"banjo", hint:"no hint"},
    {word:"bayou", hint:"no hint"},
    {word:"beekeeper", hint:"no hint"},
    {word:"bikini", hint:"no hint"},
    {word:"blitz", hint:"no hint"},
    {word:"blizzard", hint:"no hint"},
    {word:"boggle", hint:"no hint"},
    {word:"bookworm", hint:"no hint"},
    {word:"boxcar", hint:"no hint"},
    {word:"boxful", hint:"no hint"},
    {word:"buckaroo", hint:"no hint"},
    {word:"buffalo", hint:"no hint"},
    {word:"buffoon", hint:"no hint"},
    {word:"buxom", hint:"no hint"},
    {word:"buzzard", hint:"no hint"},
    {word:"buzzing", hint:"no hint"},
    {word:"buzzwords", hint:"no hint"},
    {word:"caliph", hint:"no hint"},
    {word:"cobweb", hint:"no hint"},
    {word:"cockiness", hint:"no hint"},
    {word:"croquet", hint:"no hint"},
    {word:"crypt", hint:"no hint"},
    {word:"curacao", hint:"no hint"},
    {word:"cycle", hint:"no hint"},
    {word:"daiquiri", hint:"no hint"},
    {word:"dirndl", hint:"no hint"},
    {word:"disavow", hint:"no hint"},
    {word:"dizzying", hint:"no hint"},
    {word:"duplex", hint:"no hint"},
    {word:"dwarves", hint:"no hint"},
    {word:"embezzle", hint:"no hint"},
    {word:"equip", hint:"no hint"},
    {word:"espionage", hint:"no hint"},
    {word:"euouae", hint:"no hint"},
    {word:"exodus", hint:"no hint"},
    {word:"faking", hint:"no hint"},
    {word:"fishhook", hint:"no hint"},
    {word:"fixable", hint:"no hint"},
    {word:"fjord", hint:"no hint"},
    {word:"flapjack", hint:"no hint"},
    {word:"flopping", hint:"no hint"},
    {word:"fluffiness", hint:"no hint"},
    {word:"flyby", hint:"no hint"},
    {word:"foxglove", hint:"no hint"},
    {word:"frazzled", hint:"no hint"},
    {word:"frizzled", hint:"no hint"},
    {word:"fuchsia", hint:"no hint"},
    {word:"funny", hint:"no hint"},
    {word:"gabby", hint:"no hint"},
    {word:"galaxy", hint:"no hint"},
    {word:"galvanize", hint:"no hint"},
    {word:"gazebo", hint:"no hint"},
    {word:"giaour", hint:"no hint"},
    {word:"gizmo", hint:"no hint"},
    {word:"glowworm", hint:"no hint"},
    {word:"glyph", hint:"no hint"},
    {word:"gnarly", hint:"no hint"},
    {word:"gnostic", hint:"no hint"},
    {word:"gossip", hint:"no hint"},
    {word:"grogginess", hint:"no hint"},
    {word:"haiku", hint:"no hint"},
    {word:"haphazard", hint:"no hint"},
    {word:"hyphen", hint:"no hint"},
    {word:"iatrogenic", hint:"no hint"},
    {word:"icebox", hint:"no hint"},
    {word:"injury", hint:"no hint"},
    {word:"ivory", hint:"no hint"},
    {word:"ivy", hint:"no hint"},
    {word:"jackpot", hint:"no hint"},
    {word:"jaundice", hint:"no hint"},
    {word:"jawbreaker", hint:"no hint"},
    {word:"jaywalk", hint:"no hint"},
    {word:"jazziest", hint:"no hint"},
    {word:"jazzy", hint:"no hint"},
    {word:"jelly", hint:"no hint"},
    {word:"jigsaw", hint:"no hint"},
    {word:"jinx", hint:"no hint"},
    {word:"jiujitsu", hint:"no hint"},
    {word:"jockey", hint:"no hint"},
    {word:"jogging", hint:"no hint"},
    {word:"joking", hint:"no hint"},
    {word:"jovial", hint:"no hint"},
    {word:"joyful", hint:"no hint"},
    {word:"juicy", hint:"no hint"},
    {word:"jukebox", hint:"no hint"},
    {word:"jumbo", hint:"no hint"},
    {word:"kayak", hint:"no hint"},
    {word:"kazoo", hint:"no hint"},
    {word:"keyhole", hint:"no hint"},
    {word:"khaki", hint:"no hint"},
    {word:"kilobyte", hint:"no hint"},
    {word:"kiosk", hint:"no hint"},
    {word:"kitsch", hint:"no hint"},
    {word:"kiwifruit", hint:"no hint"},
    {word:"klutz", hint:"no hint"},
    {word:"knapsack", hint:"no hint"},
    {word:"larynx", hint:"no hint"},
    {word:"lengths", hint:"no hint"},
    {word:"lucky", hint:"no hint"},
    {word:"luxury", hint:"no hint"},
    {word:"lymph", hint:"no hint"},
    {word:"marquis", hint:"no hint"},
    {word:"matrix", hint:"no hint"},
    {word:"megahertz", hint:"no hint"},
    {word:"microwave", hint:"no hint"},
    {word:"mnemonic", hint:"no hint"},
    {word:"mystify", hint:"no hint"},
    {word:"naphtha", hint:"no hint"},
    {word:"nightclub", hint:"no hint"},
    {word:"nowadays", hint:"no hint"},
    {word:"numbskull", hint:"no hint"},
    {word:"nymph", hint:"no hint"},
    {word:"onyx", hint:"no hint"},
    {word:"ovary", hint:"no hint"},
    {word:"oxidize", hint:"no hint"},
    {word:"oxygen", hint:"no hint"},
    {word:"pajama", hint:"no hint"},
    {word:"peekaboo", hint:"no hint"},
    {word:"phlegm", hint:"no hint"},
    {word:"pixel", hint:"no hint"},
    {word:"pizazz", hint:"no hint"},
    {word:"pneumonia", hint:"no hint"},
    {word:"polka", hint:"no hint"},
    {word:"pshaw", hint:"no hint"},
    {word:"psyche", hint:"no hint"},
    {word:"puppy", hint:"no hint"},
    {word:"puzzling", hint:"no hint"},
    {word:"quartz", hint:"no hint"},
    {word:"queue", hint:"no hint"},
    {word:"quips", hint:"no hint"},
    {word:"quixotic", hint:"no hint"},
    {word:"quiz", hint:"no hint"},
    {word:"quizzes", hint:"no hint"},
    {word:"quorum", hint:"no hint"},
    {word:"razzmatazz", hint:"no hint"},
    {word:"rhubarb", hint:"no hint"},
    {word:"rhythm", hint:"no hint"},
    {word:"rickshaw", hint:"no hint"},
    {word:"schnapps", hint:"no hint"},
    {word:"scratch", hint:"no hint"},
    {word:"shiv", hint:"no hint"},
    {word:"snazzy", hint:"no hint"},
    {word:"sphinx", hint:"no hint"},
    {word:"spritz", hint:"no hint"},
    {word:"squawk", hint:"no hint"},
    {word:"staff", hint:"no hint"},
    {word:"strength", hint:"no hint"},
    {word:"strengths", hint:"no hint"},
    {word:"stretch", hint:"no hint"},
    {word:"stronghold", hint:"no hint"},
    {word:"stymied", hint:"no hint"},
    {word:"subway", hint:"no hint"},
    {word:"swivel", hint:"no hint"},
    {word:"syndrome", hint:"no hint"},
    {word:"thriftless", hint:"no hint"},
    {word:"thumbscrew", hint:"no hint"},
    {word:"topaz", hint:"no hint"},
    {word:"transcript", hint:"no hint"},
    {word:"transgress", hint:"no hint"},
    {word:"transplant", hint:"no hint"},
    {word:"triphthong", hint:"no hint"},
    {word:"twelfth", hint:"no hint"},
    {word:"twelfths", hint:"no hint"},
    {word:"unknown", hint:"no hint"},
    {word:"unworthy", hint:"no hint"},
    {word:"unzip", hint:"no hint"},
    {word:"uptown", hint:"no hint"},
    {word:"vaporize", hint:"no hint"},
    {word:"vixen", hint:"no hint"},
    {word:"vodka", hint:"no hint"},
    {word:"voodoo", hint:"no hint"},
    {word:"vortex", hint:"no hint"},
    {word:"voyeurism", hint:"no hint"},
    {word:"walkway", hint:"no hint"},
    {word:"waltz", hint:"no hint"},
    {word:"wave", hint:"no hint"},
    {word:"wavy", hint:"no hint"},
    {word:"waxy", hint:"no hint"},
    {word:"wellspring", hint:"no hint"},
    {word:"wheezy", hint:"no hint"},
    {word:"whiskey", hint:"no hint"},
    {word:"whizzing", hint:"no hint"},
    {word:"whomever", hint:"no hint"},
    {word:"wimpy", hint:"no hint"},
    {word:"witchcraft", hint:"no hint"},
    {word:"wizard", hint:"no hint"},
    {word:"woozy", hint:"no hint"},
    {word:"wristwatch", hint:"no hint"},
    {word:"wyvern", hint:"no hint"},
    {word:"xylophone", hint:"no hint"},
    {word:"yachtsman", hint:"no hint"},
    {word:"yippee", hint:"no hint"},
    {word:"yoked", hint:"no hint"},
    {word:"youthful", hint:"no hint"},
    {word:"yummy", hint:"no hint"},
    {word:"zephyr", hint:"no hint"},
    {word:"zigzag", hint:"no hint"},
    {word:"zigzagging", hint:"no hint"},
    {word:"zilch", hint:"no hint"},
    {word:"zipper", hint:"no hint"},
    {word:"zodiac", hint:"no hint"},
    {word:"zombie", hint:"no hint"},
    {word:"about", hint:"no hint"},
    {word:"above", hint:"no hint"},
    {word:"abuse", hint:"no hint"},
    {word:"accept", hint:"no hint"},
    {word:"accident", hint:"no hint"},
    {word:"accuse", hint:"no hint"},
    {word:"across", hint:"no hint"},
    {word:"activist", hint:"no hint"},
    {word:"actor", hint:"no hint"},
    {word:"administration", hint:"no hint"},
    {word:"admit", hint:"no hint"},
    {word:"adult", hint:"no hint"},
    {word:"advertise", hint:"no hint"},
    {word:"advise", hint:"no hint"},
    {word:"affect", hint:"no hint"},
    {word:"afraid", hint:"no hint"},
    {word:"after", hint:"no hint"},
    {word:"again", hint:"no hint"},
    {word:"against", hint:"no hint"},
    {word:"agency", hint:"no hint"},
    {word:"aggression", hint:"no hint"},
    {word:"agree", hint:"no hint"},
    {word:"agriculture", hint:"no hint"},
    {word:"force", hint:"no hint"},
    {word:"airplane", hint:"no hint"},
    {word:"airport", hint:"no hint"},
    {word:"album", hint:"no hint"},
    {word:"alcohol", hint:"no hint"},
    {word:"alive", hint:"no hint"},
    {word:"almost", hint:"no hint"},
    {word:"alone", hint:"no hint"},
    {word:"along", hint:"no hint"},
    {word:"already", hint:"no hint"},
    {word:"although", hint:"no hint"},
    {word:"always", hint:"no hint"},
    {word:"ambassador", hint:"no hint"},
    {word:"amend", hint:"no hint"},
    {word:"ammunition", hint:"no hint"},
    {word:"among", hint:"no hint"},
    {word:"amount", hint:"no hint"},
    {word:"anarchy", hint:"no hint"},
    {word:"ancestor", hint:"no hint"},
    {word:"ancient", hint:"no hint"},
    {word:"anger", hint:"no hint"},
    {word:"animal", hint:"no hint"},
    {word:"anniversary", hint:"no hint"},
    {word:"announce", hint:"no hint"},
    {word:"another", hint:"no hint"},
    {word:"answer", hint:"no hint"},
    {word:"apologize", hint:"no hint"},
    {word:"appeal", hint:"no hint"},
    {word:"appear", hint:"no hint"},
    {word:"appoint", hint:"no hint"},
    {word:"approve", hint:"no hint"},
    {word:"archeology", hint:"no hint"},
    {word:"argue", hint:"no hint"},
    {word:"around", hint:"no hint"},
    {word:"arrest", hint:"no hint"},
    {word:"arrive", hint:"no hint"},
    {word:"artillery", hint:"no hint"},
    {word:"assist", hint:"no hint"},
    {word:"astronaut", hint:"no hint"},
    {word:"astronomy", hint:"no hint"},
    {word:"asylum", hint:"no hint"},
    {word:"atmosphere", hint:"no hint"},
    {word:"attach", hint:"no hint"},
    {word:"attack", hint:"no hint"},
    {word:"attempt", hint:"no hint"},
    {word:"attend", hint:"no hint"},
    {word:"attention", hint:"no hint"},
    {word:"automobile", hint:"no hint"},
    {word:"autumn", hint:"no hint"},
    {word:"available", hint:"no hint"},
    {word:"average", hint:"no hint"},
    {word:"avoid", hint:"no hint"},
    {word:"awake", hint:"no hint"},
    {word:"award", hint:"no hint"},
    {word:"balance", hint:"no hint"},
    {word:"balloon", hint:"no hint"},
    {word:"ballot", hint:"no hint"},
    {word:"barrier", hint:"no hint"},
    {word:"battle", hint:"no hint"},
    {word:"beauty", hint:"no hint"},
    {word:"because", hint:"no hint"},
    {word:"become", hint:"no hint"},
    {word:"before", hint:"no hint"},
    {word:"begin", hint:"no hint"},
    {word:"behavior", hint:"no hint"},
    {word:"behind", hint:"no hint"},
    {word:"believe", hint:"no hint"},
    {word:"belong", hint:"no hint"},
    {word:"below", hint:"no hint"},
    {word:"betray", hint:"no hint"},
    {word:"better", hint:"no hint"},
    {word:"between", hint:"no hint"},
    {word:"biology", hint:"no hint"},
    {word:"black", hint:"no hint"},
    {word:"blame", hint:"no hint"},
    {word:"bleed", hint:"no hint"},
    {word:"blind", hint:"no hint"},
    {word:"block", hint:"no hint"},
    {word:"blood", hint:"no hint"},
    {word:"border", hint:"no hint"},
    {word:"borrow", hint:"no hint"},
    {word:"bottle", hint:"no hint"},
    {word:"bottom", hint:"no hint"},
    {word:"boycott", hint:"no hint"},
    {word:"brain", hint:"no hint"},
    {word:"brave", hint:"no hint"},
    {word:"bread", hint:"no hint"},
    {word:"break", hint:"no hint"},
    {word:"breathe", hint:"no hint"},
    {word:"bridge", hint:"no hint"},
    {word:"brief", hint:"no hint"},
    {word:"bright", hint:"no hint"},
    {word:"bring", hint:"no hint"},
    {word:"broadcast", hint:"no hint"},
    {word:"brother", hint:"no hint"},
    {word:"brown", hint:"no hint"},
    {word:"budget", hint:"no hint"},
    {word:"build", hint:"no hint"},
    {word:"building", hint:"no hint"},
    {word:"bullet", hint:"no hint"},
    {word:"burst", hint:"no hint"},
    {word:"business", hint:"no hint"},
    {word:"cabinet", hint:"no hint"},
    {word:"camera", hint:"no hint"},
    {word:"campaign", hint:"no hint"},
    {word:"cancel", hint:"no hint"},
    {word:"cancer", hint:"no hint"},
    {word:"candidate", hint:"no hint"},
    {word:"capital", hint:"no hint"},
    {word:"capture", hint:"no hint"},
    {word:"career", hint:"no hint"},
    {word:"careful", hint:"no hint"},
    {word:"carry", hint:"no hint"},
    {word:"catch", hint:"no hint"},
    {word:"cause", hint:"no hint"},
    {word:"ceasefire", hint:"no hint"},
    {word:"celebrate", hint:"no hint"},
    {word:"center", hint:"no hint"},
    {word:"century", hint:"no hint"},
    {word:"ceremony", hint:"no hint"},
    {word:"chairman", hint:"no hint"},
    {word:"champion", hint:"no hint"},
    {word:"chance", hint:"no hint"},
    {word:"change", hint:"no hint"},
    {word:"charge", hint:"no hint"},
    {word:"chase", hint:"no hint"},
    {word:"cheat", hint:"no hint"},
    {word:"cheer", hint:"no hint"},
    {word:"chemicals", hint:"no hint"},
    {word:"chemistry", hint:"no hint"},
    {word:"chief", hint:"no hint"},
    {word:"child", hint:"no hint"},
    {word:"children", hint:"no hint"},
    {word:"choose", hint:"no hint"},
    {word:"circle", hint:"no hint"},
    {word:"citizen", hint:"no hint"},
    {word:"civilian", hint:"no hint"},
    {word:"civil", hint:"no hint"},
    {word:"rights", hint:"no hint"},
    {word:"claim", hint:"no hint"},
    {word:"clash", hint:"no hint"},
    {word:"class", hint:"no hint"},
    {word:"clean", hint:"no hint"},
    {word:"clear", hint:"no hint"},
    {word:"clergy", hint:"no hint"},
    {word:"climate", hint:"no hint"},
    {word:"climb", hint:"no hint"},
    {word:"clock", hint:"no hint"},
    {word:"close", hint:"no hint"},
    {word:"cloth", hint:"no hint"},
    {word:"clothes", hint:"no hint"},
    {word:"cloud", hint:"no hint"},
    {word:"coalition", hint:"no hint"},
    {word:"coast", hint:"no hint"},
    {word:"coffee", hint:"no hint"},
    {word:"collapse", hint:"no hint"},
    {word:"collect", hint:"no hint"},
    {word:"college", hint:"no hint"},
    {word:"colony", hint:"no hint"},
    {word:"color", hint:"no hint"},
    {word:"combine", hint:"no hint"},
    {word:"command", hint:"no hint"},
    {word:"comment", hint:"no hint"},
    {word:"committee", hint:"no hint"},
    {word:"common", hint:"no hint"},
    {word:"communicate", hint:"no hint"},
    {word:"community", hint:"no hint"},
    {word:"company", hint:"no hint"},
    {word:"compare", hint:"no hint"},
    {word:"compete", hint:"no hint"},
    {word:"complete", hint:"no hint"},
    {word:"complex", hint:"no hint"},
    {word:"compromise", hint:"no hint"},
    {word:"computer", hint:"no hint"},
    {word:"concern", hint:"no hint"},
    {word:"condemn", hint:"no hint"},
    {word:"condition", hint:"no hint"},
    {word:"conference", hint:"no hint"},
    {word:"confirm", hint:"no hint"},
    {word:"conflict", hint:"no hint"},
    {word:"congratulate", hint:"no hint"},
    {word:"Congress", hint:"no hint"},
    {word:"connect", hint:"no hint"},
    {word:"conservative", hint:"no hint"},
    {word:"consider", hint:"no hint"},
    {word:"constitution", hint:"no hint"},
    {word:"contact", hint:"no hint"},
    {word:"contain", hint:"no hint"},
    {word:"container", hint:"no hint"},
    {word:"continent", hint:"no hint"},
    {word:"continue", hint:"no hint"},
    {word:"control", hint:"no hint"},
    {word:"convention", hint:"no hint"},
    {word:"cooperate", hint:"no hint"},
    {word:"correct", hint:"no hint"},
    {word:"corruption", hint:"no hint"},
    {word:"cotton", hint:"no hint"},
    {word:"count", hint:"no hint"},
    {word:"country", hint:"no hint"},
    {word:"court", hint:"no hint"},
    {word:"cover", hint:"no hint"},
    {word:"crash", hint:"no hint"},
    {word:"create", hint:"no hint"},
    {word:"creature", hint:"no hint"},
    {word:"credit", hint:"no hint"},
    {word:"crime", hint:"no hint"},
    {word:"criminal", hint:"no hint"},
    {word:"crisis", hint:"no hint"},
    {word:"criticize", hint:"no hint"},
    {word:"crops", hint:"no hint"},
    {word:"cross", hint:"no hint"},
    {word:"crowd", hint:"no hint"},
    {word:"crush", hint:"no hint"},
    {word:"culture", hint:"no hint"},
    {word:"curfew", hint:"no hint"},
    {word:"current", hint:"no hint"},
    {word:"custom", hint:"no hint"},
    {word:"customs", hint:"no hint"},
    {word:"damage", hint:"no hint"},
    {word:"dance", hint:"no hint"},
    {word:"danger", hint:"no hint"},
    {word:"daughter", hint:"no hint"},
    {word:"debate", hint:"no hint"},
    {word:"decide", hint:"no hint"},
    {word:"declare", hint:"no hint"},
    {word:"decrease", hint:"no hint"},
    {word:"defeat", hint:"no hint"},
    {word:"defend", hint:"no hint"},
    {word:"deficit", hint:"no hint"},
    {word:"define", hint:"no hint"},
    {word:"degree", hint:"no hint"},
    {word:"delay", hint:"no hint"},
    {word:"delegate", hint:"no hint"},
    {word:"demand", hint:"no hint"},
    {word:"democracy", hint:"no hint"},
    {word:"demonstrate", hint:"no hint"},
    {word:"denounce", hint:"no hint"},
    {word:"depend", hint:"no hint"},
    {word:"deplore", hint:"no hint"},
    {word:"deploy", hint:"no hint"},
    {word:"depression", hint:"no hint"},
    {word:"describe", hint:"no hint"},
    {word:"desert", hint:"no hint"},
    {word:"design", hint:"no hint"},
    {word:"desire", hint:"no hint"},
    {word:"destroy", hint:"no hint"},
    {word:"detail", hint:"no hint"},
    {word:"detain", hint:"no hint"},
    {word:"develop", hint:"no hint"},
    {word:"device", hint:"no hint"},
    {word:"dictator", hint:"no hint"},
    {word:"different", hint:"no hint"},
    {word:"difficult", hint:"no hint"},
    {word:"dinner", hint:"no hint"},
    {word:"diplomat", hint:"no hint"},
    {word:"direct", hint:"no hint"},
    {word:"direction", hint:"no hint"},
    {word:"disappear", hint:"no hint"},
    {word:"disarm", hint:"no hint"},
    {word:"disaster", hint:"no hint"},
    {word:"discover", hint:"no hint"},
    {word:"discrimination", hint:"no hint"},
    {word:"discuss", hint:"no hint"},
    {word:"disease", hint:"no hint"},
    {word:"dismiss", hint:"no hint"},
    {word:"dispute", hint:"no hint"},
    {word:"dissident", hint:"no hint"},
    {word:"distance", hint:"no hint"},
    {word:"divide", hint:"no hint"},
    {word:"doctor", hint:"no hint"},
    {word:"document", hint:"no hint"},
    {word:"dollar", hint:"no hint"},
    {word:"donate", hint:"no hint"},
    {word:"double", hint:"no hint"},
    {word:"dream", hint:"no hint"},
    {word:"drink", hint:"no hint"},
    {word:"drive", hint:"no hint"},
    {word:"drown", hint:"no hint"},
    {word:"during", hint:"no hint"},
    {word:"early", hint:"no hint"},
    {word:"earth", hint:"no hint"},
    {word:"earthquake", hint:"no hint"},
    {word:"ecology", hint:"no hint"},
    {word:"economy", hint:"no hint"},
    {word:"education", hint:"no hint"},
    {word:"effect", hint:"no hint"},
    {word:"effort", hint:"no hint"},
    {word:"either", hint:"no hint"},
    {word:"elect", hint:"no hint"},
    {word:"electricity", hint:"no hint"},
    {word:"embassy", hint:"no hint"},
    {word:"embryo", hint:"no hint"},
    {word:"emergency", hint:"no hint"},
    {word:"emotion", hint:"no hint"},
    {word:"employ", hint:"no hint"},
    {word:"empty", hint:"no hint"},
    {word:"enemy", hint:"no hint"},
    {word:"energy", hint:"no hint"},
    {word:"enforce", hint:"no hint"},
    {word:"engine", hint:"no hint"},
    {word:"engineer", hint:"no hint"},
    {word:"enjoy", hint:"no hint"},
    {word:"enough", hint:"no hint"},
    {word:"enter", hint:"no hint"},
    {word:"environment", hint:"no hint"},
    {word:"equal", hint:"no hint"},
    {word:"equipment", hint:"no hint"},
    {word:"escape", hint:"no hint"},
    {word:"especially", hint:"no hint"},
    {word:"establish", hint:"no hint"},
    {word:"estimate", hint:"no hint"},
    {word:"ethnic", hint:"no hint"},
    {word:"evaporate", hint:"no hint"},
    {word:"event", hint:"no hint"},
    {word:"every", hint:"no hint"},
    {word:"evidence", hint:"no hint"},
    {word:"exact", hint:"no hint"},
    {word:"examine", hint:"no hint"},
    {word:"example", hint:"no hint"},
    {word:"excellent", hint:"no hint"},
    {word:"except", hint:"no hint"},
    {word:"exchange", hint:"no hint"},
    {word:"excuse", hint:"no hint"},
    {word:"execute", hint:"no hint"},
    {word:"exercise", hint:"no hint"},
    {word:"exile", hint:"no hint"},
    {word:"exist", hint:"no hint"},
    {word:"expand", hint:"no hint"},
    {word:"expect", hint:"no hint"},
    {word:"expel", hint:"no hint"},
    {word:"experience", hint:"no hint"},
    {word:"experiment", hint:"no hint"},
    {word:"expert", hint:"no hint"},
    {word:"explain", hint:"no hint"},
    {word:"explode", hint:"no hint"},
    {word:"explore", hint:"no hint"},
    {word:"export", hint:"no hint"},
    {word:"express", hint:"no hint"},
    {word:"extend", hint:"no hint"},
    {word:"extra", hint:"no hint"},
    {word:"extraordinary", hint:"no hint"},
    {word:"extreme", hint:"no hint"},
    {word:"extremist", hint:"no hint"},
    {word:"factory", hint:"no hint"},
    {word:"false", hint:"no hint"},
    {word:"family", hint:"no hint"},
    {word:"famous", hint:"no hint"},
    {word:"father", hint:"no hint"},
    {word:"favorite", hint:"no hint"},
    {word:"federal", hint:"no hint"},
    {word:"female", hint:"no hint"},
    {word:"fence", hint:"no hint"},
    {word:"fertile", hint:"no hint"},
    {word:"field", hint:"no hint"},
    {word:"fierce", hint:"no hint"},
    {word:"fight", hint:"no hint"},
    {word:"final", hint:"no hint"},
    {word:"financial", hint:"no hint"},
    {word:"finish", hint:"no hint"},
    {word:"fireworks", hint:"no hint"},
    {word:"first", hint:"no hint"},
    {word:"float", hint:"no hint"},
    {word:"flood", hint:"no hint"},
    {word:"floor", hint:"no hint"},
    {word:"flower", hint:"no hint"},
    {word:"fluid", hint:"no hint"},
    {word:"follow", hint:"no hint"},
    {word:"force", hint:"no hint"},
    {word:"foreign", hint:"no hint"},
    {word:"forest", hint:"no hint"},
    {word:"forget", hint:"no hint"},
    {word:"forgive", hint:"no hint"},
    {word:"former", hint:"no hint"},
    {word:"forward", hint:"no hint"},
    {word:"freedom", hint:"no hint"},
    {word:"freeze", hint:"no hint"},
    {word:"fresh", hint:"no hint"},
    {word:"friend", hint:"no hint"},
    {word:"frighten", hint:"no hint"},
    {word:"front", hint:"no hint"},
    {word:"fruit", hint:"no hint"},
    {word:"funeral", hint:"no hint"},
    {word:"future", hint:"no hint"},
    {word:"gather", hint:"no hint"},
    {word:"general", hint:"no hint"},
    {word:"generation", hint:"no hint"},
    {word:"genocide", hint:"no hint"},
    {word:"gentle", hint:"no hint"},
    {word:"glass", hint:"no hint"},
    {word:"goods", hint:"no hint"},
    {word:"govern", hint:"no hint"},
    {word:"government", hint:"no hint"},
    {word:"grain", hint:"no hint"},
    {word:"grass", hint:"no hint"},
    {word:"great", hint:"no hint"},
    {word:"green", hint:"no hint"},
    {word:"grind", hint:"no hint"},
    {word:"ground", hint:"no hint"},
    {word:"group", hint:"no hint"},
    {word:"guarantee", hint:"no hint"},
    {word:"guard", hint:"no hint"},
    {word:"guerrilla", hint:"no hint"},
    {word:"guide", hint:"no hint"},
    {word:"guilty", hint:"no hint"},
    {word:"happen", hint:"no hint"},
    {word:"happy", hint:"no hint"},
    {word:"harvest", hint:"no hint"},
    {word:"headquarters", hint:"no hint"},
    {word:"health", hint:"no hint"},
    {word:"heavy", hint:"no hint"},
    {word:"helicopter", hint:"no hint"},
    {word:"hijack", hint:"no hint"},
    {word:"history", hint:"no hint"},
    {word:"holiday", hint:"no hint"},
    {word:"honest", hint:"no hint"},
    {word:"honor", hint:"no hint"},
    {word:"horrible", hint:"no hint"},
    {word:"horse", hint:"no hint"},
    {word:"hospital", hint:"no hint"},
    {word:"hostage", hint:"no hint"},
    {word:"hostile", hint:"no hint"},
    {word:"hotel", hint:"no hint"},
    {word:"house", hint:"no hint"},
    {word:"however", hint:"no hint"},
    {word:"human", hint:"no hint"},
    {word:"humor", hint:"no hint"},
    {word:"hunger", hint:"no hint"},
    {word:"hurry", hint:"no hint"},
    {word:"husband", hint:"no hint"},
    {word:"identify", hint:"no hint"},
    {word:"ignore", hint:"no hint"},
    {word:"illegal", hint:"no hint"},
    {word:"imagine", hint:"no hint"},
    {word:"immediate", hint:"no hint"},
    {word:"immigrant", hint:"no hint"},
    {word:"import", hint:"no hint"},
    {word:"important", hint:"no hint"},
    {word:"improve", hint:"no hint"},
    {word:"incident", hint:"no hint"},
    {word:"incite", hint:"no hint"},
    {word:"include", hint:"no hint"},
    {word:"increase", hint:"no hint"},
    {word:"independent", hint:"no hint"},
    {word:"individual", hint:"no hint"},
    {word:"industry", hint:"no hint"},
    {word:"infect", hint:"no hint"},
    {word:"inflation", hint:"no hint"},
    {word:"influence", hint:"no hint"},
    {word:"inform", hint:"no hint"},
    {word:"information", hint:"no hint"},
    {word:"inject", hint:"no hint"},
    {word:"injure", hint:"no hint"},
    {word:"innocent", hint:"no hint"},
    {word:"insane", hint:"no hint"},
    {word:"insect", hint:"no hint"},
    {word:"inspect", hint:"no hint"},
    {word:"instead", hint:"no hint"},
    {word:"instrument", hint:"no hint"},
    {word:"insult", hint:"no hint"},
    {word:"intelligence", hint:"no hint"},
    {word:"intelligent", hint:"no hint"},
    {word:"intense", hint:"no hint"},
    {word:"interest", hint:"no hint"},
    {word:"interfere", hint:"no hint"},
    {word:"international", hint:"no hint"},
    {word:"Internet", hint:"no hint"},
    {word:"intervene", hint:"no hint"},
    {word:"invade", hint:"no hint"},
    {word:"invent", hint:"no hint"},
    {word:"invest", hint:"no hint"},
    {word:"investigate", hint:"no hint"},
    {word:"invite", hint:"no hint"},
    {word:"involve", hint:"no hint"},
    {word:"island", hint:"no hint"},
    {word:"issue", hint:"no hint"},
    {word:"jewel", hint:"no hint"},
    {word:"joint", hint:"no hint"},
    {word:"judge", hint:"no hint"},
    {word:"justice", hint:"no hint"},
    {word:"kidnap", hint:"no hint"},
    {word:"knife", hint:"no hint"},
    {word:"knowledge", hint:"no hint"},
    {word:"labor", hint:"no hint"},
    {word:"laboratory", hint:"no hint"},
    {word:"language", hint:"no hint"},
    {word:"large", hint:"no hint"},
    {word:"laugh", hint:"no hint"},
    {word:"launch", hint:"no hint"},
    {word:"learn", hint:"no hint"},
    {word:"leave", hint:"no hint"},
    {word:"legal", hint:"no hint"},
    {word:"legislature", hint:"no hint"},
    {word:"letter", hint:"no hint"},
    {word:"level", hint:"no hint"},
    {word:"liberal", hint:"no hint"},
    {word:"light", hint:"no hint"},
    {word:"lightning", hint:"no hint"},
    {word:"limit", hint:"no hint"},
    {word:"liquid", hint:"no hint"},
    {word:"listen", hint:"no hint"},
    {word:"literature", hint:"no hint"},
    {word:"little", hint:"no hint"},
    {word:"local", hint:"no hint"},
    {word:"lonely", hint:"no hint"},
    {word:"loyal", hint:"no hint"},
    {word:"machine", hint:"no hint"},
    {word:"magazine", hint:"no hint"},
    {word:"major", hint:"no hint"},
    {word:"majority", hint:"no hint"},
    {word:"manufacture", hint:"no hint"},
    {word:"march", hint:"no hint"},
    {word:"market", hint:"no hint"},
    {word:"marry", hint:"no hint"},
    {word:"material", hint:"no hint"},
    {word:"mathematics", hint:"no hint"},
    {word:"matter", hint:"no hint"},
    {word:"mayor", hint:"no hint"},
    {word:"measure", hint:"no hint"},
    {word:"media", hint:"no hint"},
    {word:"medicine", hint:"no hint"},
    {word:"member", hint:"no hint"},
    {word:"memorial", hint:"no hint"},
    {word:"memory", hint:"no hint"},
    {word:"mental", hint:"no hint"},
    {word:"message", hint:"no hint"},
    {word:"metal", hint:"no hint"},
    {word:"method", hint:"no hint"},
    {word:"microscope", hint:"no hint"},
    {word:"middle", hint:"no hint"},
    {word:"militant", hint:"no hint"},
    {word:"military", hint:"no hint"},
    {word:"militia", hint:"no hint"},
    {word:"mineral", hint:"no hint"},
    {word:"minister", hint:"no hint"},
    {word:"minor", hint:"no hint"},
    {word:"minority", hint:"no hint"},
    {word:"minute", hint:"no hint"},
    {word:"missile", hint:"no hint"},
    {word:"missing", hint:"no hint"},
    {word:"mistake", hint:"no hint"},
    {word:"model", hint:"no hint"},
    {word:"moderate", hint:"no hint"},
    {word:"modern", hint:"no hint"},
    {word:"money", hint:"no hint"},
    {word:"month", hint:"no hint"},
    {word:"moral", hint:"no hint"},
    {word:"morning", hint:"no hint"},
    {word:"mother", hint:"no hint"},
    {word:"motion", hint:"no hint"},
    {word:"mountain", hint:"no hint"},
    {word:"mourn", hint:"no hint"},
    {word:"movement", hint:"no hint"},
    {word:"movie", hint:"no hint"},
    {word:"murder", hint:"no hint"},
    {word:"music", hint:"no hint"},
    {word:"mystery", hint:"no hint"},
    {word:"narrow", hint:"no hint"},
    {word:"nation", hint:"no hint"},
    {word:"native", hint:"no hint"},
    {word:"natural", hint:"no hint"},
    {word:"nature", hint:"no hint"},
    {word:"necessary", hint:"no hint"},
    {word:"negotiate", hint:"no hint"},
    {word:"neighbor", hint:"no hint"},
    {word:"neither", hint:"no hint"},
    {word:"neutral", hint:"no hint"},
    {word:"never", hint:"no hint"},
    {word:"night", hint:"no hint"},
    {word:"noise", hint:"no hint"},
    {word:"nominate", hint:"no hint"},
    {word:"normal", hint:"no hint"},
    {word:"north", hint:"no hint"},
    {word:"nothing", hint:"no hint"},
    {word:"nowhere", hint:"no hint"},
    {word:"nuclear", hint:"no hint"},
    {word:"number", hint:"no hint"},
    {word:"object", hint:"no hint"},
    {word:"observe", hint:"no hint"},
    {word:"occupy", hint:"no hint"},
    {word:"ocean", hint:"no hint"},
    {word:"offensive", hint:"no hint"},
    {word:"offer", hint:"no hint"},
    {word:"office", hint:"no hint"},
    {word:"officer", hint:"no hint"},
    {word:"official", hint:"no hint"},
    {word:"often", hint:"no hint"},
    {word:"operate", hint:"no hint"},
    {word:"opinion", hint:"no hint"},
    {word:"oppose", hint:"no hint"},
    {word:"opposite", hint:"no hint"},
    {word:"oppress", hint:"no hint"},
    {word:"orbit", hint:"no hint"},
    {word:"order", hint:"no hint"},
    {word:"organize", hint:"no hint"},
    {word:"other", hint:"no hint"},
    {word:"overthrow", hint:"no hint"},
    {word:"paint", hint:"no hint"},
    {word:"paper", hint:"no hint"},
    {word:"parachute", hint:"no hint"},
    {word:"parade", hint:"no hint"},
    {word:"pardon", hint:"no hint"},
    {word:"parent", hint:"no hint"},
    {word:"parliament", hint:"no hint"},
    {word:"partner", hint:"no hint"},
    {word:"party", hint:"no hint"},
    {word:"passenger", hint:"no hint"},
    {word:"passport", hint:"no hint"},
    {word:"patient", hint:"no hint"},
    {word:"peace", hint:"no hint"},
    {word:"people", hint:"no hint"},
    {word:"percent", hint:"no hint"},
    {word:"perfect", hint:"no hint"},
    {word:"perform", hint:"no hint"},
    {word:"period", hint:"no hint"},
    {word:"permanent", hint:"no hint"},
    {word:"permit", hint:"no hint"},
    {word:"person", hint:"no hint"},
    {word:"persuade", hint:"no hint"},
    {word:"physical", hint:"no hint"},
    {word:"physics", hint:"no hint"},
    {word:"picture", hint:"no hint"},
    {word:"piece", hint:"no hint"},
    {word:"pilot", hint:"no hint"},
    {word:"place", hint:"no hint"},
    {word:"planet", hint:"no hint"},
    {word:"plant", hint:"no hint"},
    {word:"plastic", hint:"no hint"},
    {word:"please", hint:"no hint"},
    {word:"plenty", hint:"no hint"},
    {word:"point", hint:"no hint"},
    {word:"poison", hint:"no hint"},
    {word:"police", hint:"no hint"},
    {word:"policy", hint:"no hint"},
    {word:"politics", hint:"no hint"},
    {word:"pollute", hint:"no hint"},
    {word:"popular", hint:"no hint"},
    {word:"population", hint:"no hint"},
    {word:"position", hint:"no hint"},
    {word:"possess", hint:"no hint"},
    {word:"possible", hint:"no hint"},
    {word:"postpone", hint:"no hint"},
    {word:"poverty", hint:"no hint"},
    {word:"power", hint:"no hint"},
    {word:"praise", hint:"no hint"},
    {word:"predict", hint:"no hint"},
    {word:"pregnant", hint:"no hint"},
    {word:"present", hint:"no hint"},
    {word:"president", hint:"no hint"},
    {word:"press", hint:"no hint"},
    {word:"pressure", hint:"no hint"},
    {word:"prevent", hint:"no hint"},
    {word:"price", hint:"no hint"},
    {word:"prison", hint:"no hint"},
    {word:"private", hint:"no hint"},
    {word:"prize", hint:"no hint"},
    {word:"probably", hint:"no hint"},
    {word:"problem", hint:"no hint"},
    {word:"process", hint:"no hint"},
    {word:"produce", hint:"no hint"},
    {word:"profession", hint:"no hint"},
    {word:"professor", hint:"no hint"},
    {word:"profit", hint:"no hint"},
    {word:"program", hint:"no hint"},
    {word:"progress", hint:"no hint"},
    {word:"project", hint:"no hint"},
    {word:"promise", hint:"no hint"},
    {word:"propaganda", hint:"no hint"},
    {word:"property", hint:"no hint"},
    {word:"propose", hint:"no hint"},
    {word:"protect", hint:"no hint"},
    {word:"protest", hint:"no hint"},
    {word:"prove", hint:"no hint"},
    {word:"provide", hint:"no hint"},
    {word:"public", hint:"no hint"},
    {word:"publication", hint:"no hint"},
    {word:"publish", hint:"no hint"},
    {word:"punish", hint:"no hint"},
    {word:"purchase", hint:"no hint"},
    {word:"purpose", hint:"no hint"},
    {word:"quality", hint:"no hint"},
    {word:"question", hint:"no hint"},
    {word:"quick", hint:"no hint"},
    {word:"quiet", hint:"no hint"},
    {word:"radar", hint:"no hint"},
    {word:"radiation", hint:"no hint"},
    {word:"radio", hint:"no hint"},
    {word:"railroad", hint:"no hint"},
    {word:"raise", hint:"no hint"},
    {word:"reach", hint:"no hint"},
    {word:"react", hint:"no hint"},
    {word:"ready", hint:"no hint"},
    {word:"realistic", hint:"no hint"},
    {word:"reason", hint:"no hint"},
    {word:"reasonable", hint:"no hint"},
    {word:"rebel", hint:"no hint"},
    {word:"receive", hint:"no hint"},
    {word:"recent", hint:"no hint"},
    {word:"recession", hint:"no hint"},
    {word:"recognize", hint:"no hint"},
    {word:"record", hint:"no hint"},
    {word:"recover", hint:"no hint"},
    {word:"reduce", hint:"no hint"},
    {word:"reform", hint:"no hint"},
    {word:"refugee", hint:"no hint"},
    {word:"refuse", hint:"no hint"},
    {word:"register", hint:"no hint"},
    {word:"regret", hint:"no hint"},
    {word:"reject", hint:"no hint"},
    {word:"relations", hint:"no hint"},
    {word:"release", hint:"no hint"},
    {word:"religion", hint:"no hint"},
    {word:"remain", hint:"no hint"},
    {word:"remains", hint:"no hint"},
    {word:"remember", hint:"no hint"},
    {word:"remove", hint:"no hint"},
    {word:"repair", hint:"no hint"},
    {word:"repeat", hint:"no hint"},
    {word:"report", hint:"no hint"},
    {word:"represent", hint:"no hint"},
    {word:"repress", hint:"no hint"},
    {word:"request", hint:"no hint"},
    {word:"require", hint:"no hint"},
    {word:"rescue", hint:"no hint"},
    {word:"research", hint:"no hint"},
    {word:"resign", hint:"no hint"},
    {word:"resist", hint:"no hint"},
    {word:"resolution", hint:"no hint"},
    {word:"resource", hint:"no hint"},
    {word:"respect", hint:"no hint"},
    {word:"responsible", hint:"no hint"},
    {word:"restaurant", hint:"no hint"},
    {word:"restrain", hint:"no hint"},
    {word:"restrict", hint:"no hint"},
    {word:"result", hint:"no hint"},
    {word:"retire", hint:"no hint"},
    {word:"return", hint:"no hint"},
    {word:"revolt", hint:"no hint"},
    {word:"right", hint:"no hint"},
    {word:"river", hint:"no hint"},
    {word:"rocket", hint:"no hint"},
    {word:"rough", hint:"no hint"},
    {word:"round", hint:"no hint"},
    {word:"rubber", hint:"no hint"},
    {word:"rural", hint:"no hint"},
    {word:"sabotage", hint:"no hint"},
    {word:"sacrifice", hint:"no hint"},
    {word:"sailor", hint:"no hint"},
    {word:"satellite", hint:"no hint"},
    {word:"satisfy", hint:"no hint"},
    {word:"school", hint:"no hint"},
    {word:"science", hint:"no hint"},
    {word:"search", hint:"no hint"},
    {word:"season", hint:"no hint"},
    {word:"second", hint:"no hint"},
    {word:"secret", hint:"no hint"},
    {word:"security", hint:"no hint"},
    {word:"seeking", hint:"no hint"},
    {word:"seize", hint:"no hint"},
    {word:"Senate", hint:"no hint"},
    {word:"sense", hint:"no hint"},
    {word:"sentence", hint:"no hint"},
    {word:"separate", hint:"no hint"},
    {word:"series", hint:"no hint"},
    {word:"serious", hint:"no hint"},
    {word:"serve", hint:"no hint"},
    {word:"service", hint:"no hint"},
    {word:"settle", hint:"no hint"},
    {word:"several", hint:"no hint"},
    {word:"severe", hint:"no hint"},
    {word:"shake", hint:"no hint"},
    {word:"shape", hint:"no hint"},
    {word:"share", hint:"no hint"},
    {word:"sharp", hint:"no hint"},
    {word:"sheep", hint:"no hint"},
    {word:"shell", hint:"no hint"},
    {word:"shelter", hint:"no hint"},
    {word:"shine", hint:"no hint"},
    {word:"shock", hint:"no hint"},
    {word:"shoot", hint:"no hint"},
    {word:"short", hint:"no hint"},
    {word:"should", hint:"no hint"},
    {word:"shout", hint:"no hint"},
    {word:"shrink", hint:"no hint"},
    {word:"sickness", hint:"no hint"},
    {word:"signal", hint:"no hint"},
    {word:"silence", hint:"no hint"},
    {word:"silver", hint:"no hint"},
    {word:"similar", hint:"no hint"},
    {word:"simple", hint:"no hint"},
    {word:"since", hint:"no hint"},
    {word:"single", hint:"no hint"},
    {word:"sister", hint:"no hint"},
    {word:"situation", hint:"no hint"},
    {word:"skeleton", hint:"no hint"},
    {word:"skill", hint:"no hint"},
    {word:"slave", hint:"no hint"},
    {word:"sleep", hint:"no hint"},
    {word:"slide", hint:"no hint"},
    {word:"small", hint:"no hint"},
    {word:"smash", hint:"no hint"},
    {word:"smell", hint:"no hint"},
    {word:"smoke", hint:"no hint"},
    {word:"smooth", hint:"no hint"},
    {word:"social", hint:"no hint"},
    {word:"soldier", hint:"no hint"},
    {word:"solid", hint:"no hint"},
    {word:"solve", hint:"no hint"},
    {word:"sound", hint:"no hint"},
    {word:"south", hint:"no hint"},
    {word:"space", hint:"no hint"},
    {word:"speak", hint:"no hint"},
    {word:"special", hint:"no hint"},
    {word:"speech", hint:"no hint"},
    {word:"speed", hint:"no hint"},
    {word:"spend", hint:"no hint"},
    {word:"spill", hint:"no hint"},
    {word:"spirit", hint:"no hint"},
    {word:"split", hint:"no hint"},
    {word:"sport", hint:"no hint"},
    {word:"spread", hint:"no hint"},
    {word:"spring", hint:"no hint"},
    {word:"square", hint:"no hint"},
    {word:"stand", hint:"no hint"},
    {word:"start", hint:"no hint"},
    {word:"starve", hint:"no hint"},
    {word:"state", hint:"no hint"},
    {word:"station", hint:"no hint"},
    {word:"statue", hint:"no hint"},
    {word:"steal", hint:"no hint"},
    {word:"steam", hint:"no hint"},
    {word:"steel", hint:"no hint"},
    {word:"stick", hint:"no hint"},
    {word:"still", hint:"no hint"},
    {word:"stone", hint:"no hint"},
    {word:"store", hint:"no hint"},
    {word:"storm", hint:"no hint"},
    {word:"story", hint:"no hint"},
    {word:"stove", hint:"no hint"},
    {word:"straight", hint:"no hint"},
    {word:"strange", hint:"no hint"},
    {word:"street", hint:"no hint"},
    {word:"stretch", hint:"no hint"},
    {word:"strike", hint:"no hint"},
    {word:"strong", hint:"no hint"},
    {word:"structure", hint:"no hint"},
    {word:"struggle", hint:"no hint"},
    {word:"study", hint:"no hint"},
    {word:"stupid", hint:"no hint"},
    {word:"subject", hint:"no hint"},
    {word:"submarine", hint:"no hint"},
    {word:"substance", hint:"no hint"},
    {word:"substitute", hint:"no hint"},
    {word:"subversion", hint:"no hint"},
    {word:"succeed", hint:"no hint"},
    {word:"sudden", hint:"no hint"},
    {word:"suffer", hint:"no hint"},
    {word:"sugar", hint:"no hint"},
    {word:"suggest", hint:"no hint"},
    {word:"suicide", hint:"no hint"},
    {word:"summer", hint:"no hint"},
    {word:"supervise", hint:"no hint"},
    {word:"supply", hint:"no hint"},
    {word:"support", hint:"no hint"},
    {word:"suppose", hint:"no hint"},
    {word:"suppress", hint:"no hint"},
    {word:"surface", hint:"no hint"},
    {word:"surplus", hint:"no hint"},
    {word:"surprise", hint:"no hint"},
    {word:"surrender", hint:"no hint"},
    {word:"surround", hint:"no hint"},
    {word:"survive", hint:"no hint"},
    {word:"suspect", hint:"no hint"},
    {word:"suspend", hint:"no hint"},
    {word:"swallow", hint:"no hint"},
    {word:"swear", hint:"no hint"},
    {word:"sweet", hint:"no hint"},
    {word:"sympathy", hint:"no hint"},
    {word:"system", hint:"no hint"},
    {word:"target", hint:"no hint"},
    {word:"taste", hint:"no hint"},
    {word:"teach", hint:"no hint"},
    {word:"technical", hint:"no hint"},
    {word:"technology", hint:"no hint"},
    {word:"telephone", hint:"no hint"},
    {word:"telescope", hint:"no hint"},
    {word:"television", hint:"no hint"},
    {word:"temperature", hint:"no hint"},
    {word:"temporary", hint:"no hint"},
    {word:"tense", hint:"no hint"},
    {word:"terrible", hint:"no hint"},
    {word:"territory", hint:"no hint"},
    {word:"terror", hint:"no hint"},
    {word:"terrorist", hint:"no hint"},
    {word:"thank", hint:"no hint"},
    {word:"theater", hint:"no hint"},
    {word:"theory", hint:"no hint"},
    {word:"there", hint:"no hint"},
    {word:"these", hint:"no hint"},
    {word:"thick", hint:"no hint"},
    {word:"thing", hint:"no hint"},
    {word:"think", hint:"no hint"},
    {word:"third", hint:"no hint"},
    {word:"threaten", hint:"no hint"},
    {word:"through", hint:"no hint"},
    {word:"throw", hint:"no hint"},
    {word:"tired", hint:"no hint"},
    {word:"today", hint:"no hint"},
    {word:"together", hint:"no hint"},
    {word:"tomorrow", hint:"no hint"},
    {word:"tonight", hint:"no hint"},
    {word:"torture", hint:"no hint"},
    {word:"total", hint:"no hint"},
    {word:"touch", hint:"no hint"},
    {word:"toward", hint:"no hint"},
    {word:"trade", hint:"no hint"},
    {word:"tradition", hint:"no hint"},
    {word:"traffic", hint:"no hint"},
    {word:"tragic", hint:"no hint"},
    {word:"train", hint:"no hint"},
    {word:"transport", hint:"no hint"},
    {word:"transportation", hint:"no hint"},
    {word:"travel", hint:"no hint"},
    {word:"treason", hint:"no hint"},
    {word:"treasure", hint:"no hint"},
    {word:"treat", hint:"no hint"},
    {word:"treatment", hint:"no hint"},
    {word:"treaty", hint:"no hint"},
    {word:"trial", hint:"no hint"},
    {word:"tribe", hint:"no hint"},
    {word:"trick", hint:"no hint"},
    {word:"troops", hint:"no hint"},
    {word:"trouble", hint:"no hint"},
    {word:"truce", hint:"no hint"},
    {word:"truck", hint:"no hint"},
    {word:"trust", hint:"no hint"},
    {word:"under", hint:"no hint"},
    {word:"understand", hint:"no hint"},
    {word:"unite", hint:"no hint"},
    {word:"universe", hint:"no hint"},
    {word:"university", hint:"no hint"},
    {word:"unless", hint:"no hint"},
    {word:"until", hint:"no hint"},
    {word:"urgent", hint:"no hint"},
    {word:"usual", hint:"no hint"},
    {word:"vacation", hint:"no hint"},
    {word:"vaccine", hint:"no hint"},
    {word:"valley", hint:"no hint"},
    {word:"value", hint:"no hint"},
    {word:"vegetable", hint:"no hint"},
    {word:"vehicle", hint:"no hint"},
    {word:"version", hint:"no hint"},
    {word:"victim", hint:"no hint"},
    {word:"victory", hint:"no hint"},
    {word:"video", hint:"no hint"},
    {word:"village", hint:"no hint"},
    {word:"violate", hint:"no hint"},
    {word:"violence", hint:"no hint"},
    {word:"visit", hint:"no hint"},
    {word:"voice", hint:"no hint"},
    {word:"volcano", hint:"no hint"},
    {word:"volunteer", hint:"no hint"},
    {word:"wages", hint:"no hint"},
    {word:"waste", hint:"no hint"},
    {word:"watch", hint:"no hint"},
    {word:"water", hint:"no hint"},
    {word:"wealth", hint:"no hint"},
    {word:"weapon", hint:"no hint"},
    {word:"weather", hint:"no hint"},
    {word:"weigh", hint:"no hint"},
    {word:"welcome", hint:"no hint"},
    {word:"wheat", hint:"no hint"},
    {word:"wheel", hint:"no hint"},
    {word:"where", hint:"no hint"},
    {word:"whether", hint:"no hint"},
    {word:"which", hint:"no hint"},
    {word:"while", hint:"no hint"},
    {word:"white", hint:"no hint"},
    {word:"whole", hint:"no hint"},
    {word:"willing", hint:"no hint"},
    {word:"window", hint:"no hint"},
    {word:"winter", hint:"no hint"},
    {word:"withdraw", hint:"no hint"},
    {word:"without", hint:"no hint"},
    {word:"witness", hint:"no hint"},
    {word:"woman", hint:"no hint"},
    {word:"wonder", hint:"no hint"},
    {word:"wonderful", hint:"no hint"},
    {word:"world", hint:"no hint"},
    {word:"worry", hint:"no hint"},
    {word:"worse", hint:"no hint"},
    {word:"worth", hint:"no hint"},
    {word:"wound", hint:"no hint"},
    {word:"wreck", hint:"no hint"},
    {word:"wreckage", hint:"no hint"},
    {word:"write", hint:"no hint"},
    {word:"wrong", hint:"no hint"},
    {word:"yellow", hint:"no hint"},
    {word:"yesterday", hint:"no hint"},
    {word:"young", hint:"no hint"}
];